
- name: setting up application
  include_role:
    name: common
    tasks_from: app_setup

- name: setting up python
  include_role:
    name: common
    tasks_from: python_setup.yaml


- name: setting up systemd
  include_role:
    name: common
    tasks_from: systemd.yaml
