 - name: install mysql
   ansible.builtin.package:
    name: mysql-server
    state:  present

 - name: enable and start service
   ansible.builtin.service:
    name: mysqld
    enabled:  yes
    state:  started

 - name: setting root pass
   ansible.builtin.command:  mysql_secure_installation --set-root-pass {{   MYSQL_ROOT_PASSWORD }}
 