# steps to be followed to deploy new version of any application
# -> stop catalogue service
# -> remove old code
# -> download new code
# -> restart catalogue


- name: stop service
  ansible.builtin.service:
    name: "{{ component }}"
    state:  stopped

- name: remove old code
  ansible.builtin.file:
    path: /app #as our code is in /app we are deleting /app dir along with it's contents
    state: absent

# now we are again creating /app dir and adding new version of application to it
- name: creating home directory app
  ansible.builtin.file:
    path: /app
    state:  directory

- name: downloading application file
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v{{ app_version }}.zip" #app version we can provide dynamically based on our deployment release.
    dest: "/tmp/{{ component }}.zip"

- name: unzipping the file content to /app directory
  ansible.builtin.unarchive:
    src:  "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes

- name: restarting  service
  ansible.builtin.service:
    name: "{{ component }}"
    state:  restarted


